File when open file
shirou/vscode-dired pull request #22
Opened 2022-12-22 09:48 UTC by frtmelody

2022-12-26 04:17 UTC, shirou requested changes
LGTM! Could you change one comment? After that I will merge and release new version. Thank you for your contribution.

2022-12-26 04:17 UTC, shirou commented on .env
> +DISABLE_ESLINT_PLUGIN=true
Could you delete this `.env` file?

2023-01-05 02:47 UTC, qiyan2019 commented on .env
> +DISABLE_ESLINT_PLUGIN=true
Done

2023-01-07 09:31 UTC, shirou approved these changes
Thank you so much!

2023-01-07 09:32 UTC, merged